blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/gozippy/DockerRescueKit/discussions
    about: Ask questions and discuss ideas
  - name: Documentation
    url: https://github.com/gozippy/DockerRescueKit/wiki
    about: Check the docs first
