blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/dockerrescuekit/docker-rescue-kit/discussions
    about: Ask questions and discuss ideas
  - name: Documentation
    url: https://github.com/dockerrescuekit/docker-rescue-kit/wiki
    about: Check the docs first
