/**
 * Integration-test harness for the BackupService.
 *
 * Provides createTestServer(), which spins up a fresh BackupService with:
 *  - a brand-new temp DRK_DATA_DIR (so secrets.json + sqlite file don't bleed
 *    between tests and don't pollute the workspace),
 *  - the DockerService module mocked so the constructor never tries to talk
 *    to the real docker socket, and
 *  - the auto-generated API key surfaced for tests to use as `x-api-key`.
 *
 * The mock factory is intentionally self-contained (jest.mock is hoisted to
 * the top of this file at parse time, so it must not close over local vars).
 *
 * Tests should construct + tear down per `beforeEach` / `afterEach` to keep
 * the brute-force-limit bucket and SQLite state isolated.
 */

import os from 'os'
import path from 'path'
import fs from 'fs-extra'
import { v4 as uuidv4 } from 'uuid'
import type { Express } from 'express'

// ---- Mocks --------------------------------------------------------------
//
// jest.mock is hoisted to the top of the file, so it runs before BackupService
// (and its transitive imports) get a chance to do `new DockerService()`.
// The PolicyManager constructor also builds its own DockerService internally —
// since we mock the module, both wire-paths get the stub.

jest.mock('../../services/DockerService', () => ({
  DockerService: jest.fn().mockImplementation(() => ({
    ping: jest.fn().mockResolvedValue(false),
    listContainers: jest.fn().mockRejectedValue(
      Object.assign(new Error('no docker'), { code: 'ENOENT' })
    ),
    listVolumes: jest.fn().mockRejectedValue(
      Object.assign(new Error('no docker'), { code: 'ENOENT' })
    ),
    listComposeStacks: jest.fn().mockRejectedValue(
      Object.assign(new Error('no docker'), { code: 'ENOENT' })
    ),
    listImages: jest.fn().mockRejectedValue(
      Object.assign(new Error('no docker'), { code: 'ENOENT' })
    ),
    listNetworks: jest.fn().mockRejectedValue(
      Object.assign(new Error('no docker'), { code: 'ENOENT' })
    ),
    exportVolume: jest.fn().mockResolvedValue(undefined),
    exportContainer: jest.fn().mockResolvedValue(undefined),
    exportImage: jest.fn().mockResolvedValue(undefined),
    exportNetwork: jest.fn().mockResolvedValue(undefined),
    importVolume: jest.fn().mockResolvedValue(undefined),
    importImage: jest.fn().mockResolvedValue(undefined),
    importNetwork: jest.fn().mockResolvedValue('mock-net'),
  })),
}))

// Belt-and-suspenders: also mock dockerode so anything that may try to
// `new Docker()` directly (StorageFactory adapters, etc.) gets a no-op.
jest.mock('dockerode', () => {
  return jest.fn().mockImplementation(() => ({
    ping: jest.fn(),
    listContainers: jest.fn(),
    listVolumes: jest.fn(),
    listImages: jest.fn(),
    listNetworks: jest.fn(),
  }))
})

export interface TestServer {
  /** The Express app, ready for supertest(app). */
  app: Express
  /** API key generated by SecretsService on first run. */
  apiKey: string
  /** Temp data directory the service is rooted at. */
  dataDir: string
  /** Underlying BackupService instance — escape hatch for advanced tests. */
  service: any
  /** Removes the temp dir. Always safe to call (best-effort). */
  cleanup: () => Promise<void>
}

/**
 * Build a fresh BackupService instance backed by a brand-new temp dir.
 *
 * BackupService reads `DRK_DATA_DIR` inside its constructor (not at module
 * import time), so we can simply set the env var right before constructing.
 */
export async function createTestServer(): Promise<TestServer> {
  const dataDir = path.join(os.tmpdir(), `drk-test-${uuidv4()}`)
  await fs.ensureDir(dataDir)

  // BackupService reads DRK_DATA_DIR for secrets/staging AND DB_PATH for the
  // sqlite file (DB_PATH wins if set). The repo's .env file sets DB_PATH to
  // a relative path that bleeds state across tests, so we also blank it here
  // so the per-test temp dir actually owns the database.
  const prevDataDir = process.env.DRK_DATA_DIR
  const prevDbPath = process.env.DB_PATH
  process.env.DRK_DATA_DIR = dataDir

  // require lazily so any late env tweaks above are honored. NOTE: the module
  // calls dotenv.config() at load time, which will populate DB_PATH from
  // packages/backend/.env on the FIRST require. We must therefore delete
  // DB_PATH AFTER the require to ensure the constructor's env read sees the
  // dataDir-derived default.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { BackupService } = require('../../index')
  delete process.env.DB_PATH

  const service = new BackupService()

  // SecretsService writes secrets.json on first construct; read it back so
  // tests can authenticate as the freshly-generated owner.
  const secretsPath = path.join(dataDir, 'secrets.json')
  const secrets = await fs.readJson(secretsPath)
  const apiKey: string = secrets.apiKey

  const app: Express = service.app

  const cleanup = async () => {
    // Close sqlite to release the file handle on Windows before rm.
    try {
      const inner = service.db?.db
      if (inner && typeof inner.close === 'function') inner.close()
    } catch { /* ignore */ }
    try {
      service.scheduler?.stop?.()
    } catch { /* ignore */ }
    if (prevDataDir === undefined) {
      delete process.env.DRK_DATA_DIR
    } else {
      process.env.DRK_DATA_DIR = prevDataDir
    }
    if (prevDbPath === undefined) {
      delete process.env.DB_PATH
    } else {
      process.env.DB_PATH = prevDbPath
    }
    await fs.remove(dataDir).catch(() => { /* best-effort */ })
  }

  return { app, apiKey, dataDir, service, cleanup }
}

/**
 * Re-read the current api key from secrets.json. Useful after a regenerate
 * call to confirm the on-disk value matches what the rotated endpoint
 * returned.
 */
export async function readApiKey(dataDir: string): Promise<string> {
  const secrets = await fs.readJson(path.join(dataDir, 'secrets.json'))
  return secrets.apiKey
}
