import fs from 'fs-extra'
import path from 'path'
import crypto from 'crypto'

export interface Secrets {
  apiKey: string
  encryptionKey: string
  /**
   * Provenance of the encryption key, recorded on fresh creation (v1.4.2+):
   * 'env' = supplied by the operator via DRK_ENCRYPTION_KEY/ENCRYPTION_KEY,
   * 'managed' = set/rotated by the operator through the app (BYOK),
   * 'generated' = auto-generated by DRK. 'env' and 'managed' both report as
   * customer-managed. Absent on secrets.json written before provenance tracking.
   */
  keySource?: 'env' | 'managed' | 'generated'
}

/** User-facing classification of where the active encryption key came from. */
export type EncryptionKeySource = 'customer-managed' | 'generated' | 'unknown'

/**
 * Hardcoded literals that shipped as defaults in pre-1.4 builds. If an
 * EXISTING secrets.json still contains either of these, the vault was
 * encrypted with a guessable key — but we must NOT rotate it, because the
 * stored ciphertext would become undecryptable. Instead we flag it loudly
 * (boot warning + GET /api/status `securityWarnings`) so the operator can
 * rotate deliberately via a migration that re-encrypts existing data.
 */
const KNOWN_DEFAULT_API_KEY = 'rescue-kit-secret-key-2026'
const KNOWN_DEFAULT_ENCRYPTION_KEY = 'super-secret-vault-key-32-chars!!'

/**
 * Manages long-lived local secrets (API key + encryption key).
 *
 * Why: previous versions shipped a hardcoded API key and a hardcoded
 * encryption-key fallback. Any installer running with defaults exposed
 * every vault entry. Secrets are now generated on first run and stored
 * with 0600 permissions in the data directory.
 */
export class SecretsService {
  private secrets: Secrets | null = null
  private warnings: string[] = []

  constructor(private secretsPath: string) {}

  /**
   * Security warnings surfaced after load(). Empty on a healthy fresh
   * install. Populated when an existing secrets.json still holds a known
   * shipped-default value (see KNOWN_DEFAULT_* above). Read-exposed via
   * GET /api/status so the UI can nag the operator to rotate.
   */
  public getSecurityWarnings(): string[] {
    // Ensure load() has run so warnings are populated.
    this.load()
    return [...this.warnings]
  }

  public load(): Secrets {
    if (this.secrets) return this.secrets

    fs.ensureDirSync(path.dirname(this.secretsPath))

    if (fs.existsSync(this.secretsPath)) {
      const raw = fs.readFileSync(this.secretsPath, 'utf-8')
      const parsed = JSON.parse(raw) as Partial<Secrets>
      if (parsed.apiKey && parsed.encryptionKey) {
        this.secrets = {
          apiKey: parsed.apiKey,
          encryptionKey: parsed.encryptionKey,
          // Preserve recorded provenance if present; never rewrite the file.
          ...(parsed.keySource ? { keySource: parsed.keySource } : {}),
        }
        // DATA SAFETY: do NOT rotate an existing weak key — vault data already
        // encrypted with it would become unreadable. Warn instead.
        this.detectWeakDefaults(this.secrets)
        return this.secrets
      }
    }

    // Respect env overrides (Docker/Kubernetes pattern) but never fall back
    // to a hardcoded literal.
    const apiKey = process.env.DRK_API_KEY || process.env.API_KEY || this.generate(32)
    const envEncryptionKey = process.env.DRK_ENCRYPTION_KEY || process.env.ENCRYPTION_KEY
    const encryptionKey = envEncryptionKey || this.generate(32)

    this.secrets = {
      apiKey,
      encryptionKey,
      // Record provenance so the UI can show "customer-managed (BYOK)" vs
      // "auto-generated" on subsequent boots without re-checking env.
      keySource: envEncryptionKey ? 'env' : 'generated',
    }
    fs.writeFileSync(this.secretsPath, JSON.stringify(this.secrets, null, 2), { mode: 0o600 })
    try {
      fs.chmodSync(this.secretsPath, 0o600)
    } catch {
      // Windows: chmod is a best-effort; ACLs govern access there.
    }

    // Print once at startup so operators can find the bootstrap key.
    console.log(`\x1b[33m[Secrets]\x1b[0m Initialized secrets at ${this.secretsPath}`)
    console.log(`\x1b[33m[Secrets]\x1b[0m API key: ${apiKey}`)

    return this.secrets
  }

  public getApiKey(): string {
    return this.load().apiKey
  }

  public getEncryptionKey(): string {
    return this.load().encryptionKey
  }

  /**
   * Classify where the active encryption key came from, for UI display.
   * Read-only and non-destructive — this never gates decryption.
   *
   *  - 'customer-managed': operator supplied the key (BYOK). Either recorded
   *    provenance says so, or a current env key matches the stored key (which
   *    covers installs created before provenance tracking).
   *  - 'generated': DRK auto-generated the key.
   *  - 'unknown': a pre-provenance secrets.json with no matching env key — we
   *    can't truthfully claim it's customer-managed, so we don't.
   */
  public getEncryptionKeySource(): EncryptionKeySource {
    const s = this.load()
    if (s.keySource === 'env' || s.keySource === 'managed') return 'customer-managed'
    if (s.keySource === 'generated') return 'generated'
    const envKey = process.env.DRK_ENCRYPTION_KEY || process.env.ENCRYPTION_KEY
    if (envKey && envKey === s.encryptionKey) return 'customer-managed'
    return 'unknown'
  }

  /**
   * Persist a new encryption key after a successful rotation. Atomic: writes a
   * temp file then renames over secrets.json so a crash can never leave a
   * half-written secrets file. Marks provenance 'managed' (customer-managed).
   *
   * DO NOT call this directly to "rotate" — vault data is still encrypted under
   * the OLD key until re-encrypted. Use EncryptionKeyService.rotate(), which
   * re-encrypts all vault rows and only then calls this.
   */
  public setEncryptionKey(newRawKey: string): void {
    const cur = this.load()
    const next: Secrets = { ...cur, encryptionKey: newRawKey, keySource: 'managed' }
    this.atomicWriteSecrets(next)
    this.secrets = next
  }

  private atomicWriteSecrets(secrets: Secrets): void {
    const tmp = `${this.secretsPath}.tmp-${process.pid}`
    fs.writeFileSync(tmp, JSON.stringify(secrets, null, 2), { mode: 0o600 })
    fs.renameSync(tmp, this.secretsPath)
    try { fs.chmodSync(this.secretsPath, 0o600) } catch { /* Windows: ACLs */ }
  }

  // ── Key-rotation crash-recovery marker ────────────────────────────────────
  // Written before a rotation swaps the key and removed only after the rotation
  // verifies. If it survives a crash, EncryptionKeyService.recoverIfInterrupted
  // uses it on next boot to finish or roll back so data is never orphaned.
  private get rotationMarkerPath(): string {
    return path.join(path.dirname(this.secretsPath), 'key-rotation.json')
  }

  public writeRotationMarker(oldKey: string, newKey: string, startedAt: number): void {
    fs.writeFileSync(
      this.rotationMarkerPath,
      JSON.stringify({ oldKey, newKey, startedAt }, null, 2),
      { mode: 0o600 },
    )
  }

  public readRotationMarker(): { oldKey: string; newKey: string; startedAt: number } | null {
    if (!fs.existsSync(this.rotationMarkerPath)) return null
    try {
      return JSON.parse(fs.readFileSync(this.rotationMarkerPath, 'utf-8'))
    } catch {
      return null
    }
  }

  public clearRotationMarker(): void {
    try {
      if (fs.existsSync(this.rotationMarkerPath)) fs.unlinkSync(this.rotationMarkerPath)
    } catch { /* best-effort */ }
  }

  /**
   * Regenerate the API key and persist. The encryption key is intentionally
   * NOT rotated here — changing it would make every stored vault entry
   * undecryptable. Rotate that via a dedicated migration tool.
   */
  public regenerateApiKey(): string {
    const cur = this.load()
    const next: Secrets = { ...cur, apiKey: this.generate(32) }
    this.secrets = next
    fs.writeFileSync(this.secretsPath, JSON.stringify(next, null, 2), { mode: 0o600 })
    try {
      fs.chmodSync(this.secretsPath, 0o600)
    } catch { /* Windows: ignore */ }
    console.log(`\x1b[33m[Secrets]\x1b[0m API key regenerated`)
    return next.apiKey
  }

  /**
   * Flag a loaded secrets set that still carries a shipped default value.
   * Populates `this.warnings` and prints a prominent boot warning. Does not
   * mutate the secrets — rotation here would orphan existing vault ciphertext.
   */
  private detectWeakDefaults(secrets: Secrets): void {
    this.warnings = []
    if (secrets.apiKey === KNOWN_DEFAULT_API_KEY) {
      const msg =
        'Your API key is the publicly-known shipped default. Rotate it now via ' +
        'Settings → Regenerate API Key (or POST /api/settings/regenerate-api-key).'
      this.warnings.push(msg)
      console.warn(`\x1b[31m[Secrets] SECURITY WARNING:\x1b[0m ${msg}`)
    }
    if (secrets.encryptionKey === KNOWN_DEFAULT_ENCRYPTION_KEY) {
      const msg =
        'Your vault encryption key is the publicly-known shipped default. Existing ' +
        'vault data is at risk. It cannot be rotated automatically without making ' +
        'current vault entries unreadable — re-create connectors/secrets after ' +
        'manually replacing encryptionKey in secrets.json to migrate.'
      this.warnings.push(msg)
      console.warn(`\x1b[31m[Secrets] SECURITY WARNING:\x1b[0m ${msg}`)
    }
  }

  private generate(byteLen: number): string {
    return crypto.randomBytes(byteLen).toString('hex')
  }
}
