#!/usr/bin/env node
/**
 * Generates THIRD_PARTY_LICENSES.json + THIRD_PARTY_LICENSES.md from the
 * PRODUCTION dependency closure of every published workspace, plus the
 * rclone/restic binaries we compile from source and ship in the image.
 *
 * No external deps — walks the installed node_modules directly (npm hoists
 * most packages to the repo-root node_modules). Run after `npm ci`:
 *
 *   node tools/gen_licenses.js
 *
 * The output is the third-party attribution required by LICENSE §22 /
 * COMPONENTS.md. Full transitive SBOM (CycloneDX/SPDX) is a separate CI step.
 */
const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const WORKSPACES = ['packages/backend', 'packages/extension', 'packages/cli']
const INTERNAL = '@docker-rescue-kit/'
const COPYLEFT = /(^|[^A-Za-z])(GPL|AGPL|LGPL|MPL|SSPL|EUPL|CDDL)([^A-Za-z]|$)/i

const readJson = (p) => { try { return JSON.parse(fs.readFileSync(p, 'utf8')) } catch { return null } }

/** Resolve an installed package dir, honoring npm hoisting (walk up node_modules). */
function resolvePkgDir(name, fromDir) {
  let dir = fromDir
  for (;;) {
    const cand = path.join(dir, 'node_modules', name)
    if (fs.existsSync(path.join(cand, 'package.json'))) return cand
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  const rootCand = path.join(ROOT, 'node_modules', name)
  return fs.existsSync(path.join(rootCand, 'package.json')) ? rootCand : null
}

function licenseOf(pkg) {
  if (typeof pkg.license === 'string') return pkg.license
  if (pkg.license && pkg.license.type) return pkg.license.type
  if (Array.isArray(pkg.licenses) && pkg.licenses.length) {
    return pkg.licenses.map((l) => l.type || l).join(' OR ')
  }
  return 'UNKNOWN'
}

const collected = new Map() // name@version -> { name, version, license, repository }

function collect(startDeps, fromDir) {
  const queue = Object.keys(startDeps || {})
  const visited = new Set()
  while (queue.length) {
    const name = queue.shift()
    if (!name || name.startsWith(INTERNAL) || visited.has(name)) continue
    visited.add(name)
    const dir = resolvePkgDir(name, fromDir)
    if (!dir) { console.warn(`  ! not found in node_modules: ${name}`); continue }
    const pkg = readJson(path.join(dir, 'package.json'))
    if (!pkg) continue
    const key = `${pkg.name}@${pkg.version}`
    if (!collected.has(key)) {
      collected.set(key, {
        name: pkg.name,
        version: pkg.version,
        license: licenseOf(pkg),
        repository: typeof pkg.repository === 'string' ? pkg.repository : (pkg.repository && pkg.repository.url) || '',
      })
    }
    for (const d of Object.keys(pkg.dependencies || {})) {
      if (!d.startsWith(INTERNAL)) queue.push(d)
    }
  }
}

for (const ws of WORKSPACES) {
  const wsPkg = readJson(path.join(ROOT, ws, 'package.json'))
  if (!wsPkg) { console.warn(`skip missing workspace ${ws}`); continue }
  console.log(`scanning ${ws} (${Object.keys(wsPkg.dependencies || {}).length} direct prod deps)`)
  collect(wsPkg.dependencies, path.join(ROOT, ws))
}

/** Pull the pinned ARG version out of the backend Dockerfile. */
function dockerArg(name) {
  try {
    const df = fs.readFileSync(path.join(ROOT, 'packages/backend/Dockerfile'), 'utf8')
    const m = df.match(new RegExp(`ARG\\s+${name}=([\\w.\\-]+)`))
    return m ? m[1] : '(see Dockerfile)'
  } catch { return '(see Dockerfile)' }
}

const binaries = [
  { name: 'rclone', version: dockerArg('RCLONE_VERSION'), license: 'MIT', repository: 'https://github.com/rclone/rclone', note: 'Compiled from source (Dockerfile stage rclone-build).' },
  { name: 'restic', version: dockerArg('RESTIC_VERSION'), license: 'BSD-2-Clause', repository: 'https://github.com/restic/restic', note: 'Compiled from source (Dockerfile stage restic-build).' },
]

const npm = [...collected.values()].sort((a, b) => a.name.localeCompare(b.name))
const copyleft = npm.filter((d) => COPYLEFT.test(d.license))

// ── machine-readable ────────────────────────────────────────────────────
const generated = new Date().toISOString()
fs.writeFileSync(
  path.join(ROOT, 'THIRD_PARTY_LICENSES.json'),
  JSON.stringify({ generated, npmPackages: npm, bundledBinaries: binaries }, null, 2) + '\n'
)

// ── license summary ───────────────────────────────────────────────────────
const byLicense = {}
for (const d of npm) byLicense[d.license] = (byLicense[d.license] || 0) + 1
const summary = Object.entries(byLicense).sort((a, b) => b[1] - a[1])

// ── human-readable ──────────────────────────────────────────────────────
let md = `# Third-Party Licenses\n\n`
md += `> Generated by \`tools/gen_licenses.js\` on ${generated}. Do not edit by hand —\n`
md += `> run \`node tools/gen_licenses.js\` after dependency changes. Machine-readable\n`
md += `> copy: \`THIRD_PARTY_LICENSES.json\`.\n\n`
md += `Covers the **production** dependency closure of \`packages/backend\`,\n`
md += `\`packages/extension\`, and \`packages/cli\` (dev dependencies are pruned from\n`
md += `the shipped image), plus the binaries compiled into the image from source.\n\n`

md += `## License summary (npm, production closure)\n\n`
md += `| License | Packages |\n|---|---|\n`
for (const [lic, n] of summary) md += `| ${lic} | ${n} |\n`
md += `\n**Total npm packages:** ${npm.length}\n\n`
md += copyleft.length
  ? `> ⚠️ **Copyleft detected (${copyleft.length}):** ${copyleft.map((d) => `${d.name} (${d.license})`).join(', ')}. Review before redistribution.\n\n`
  : `> ✅ No GPL/AGPL/LGPL/MPL/SSPL/EUPL/CDDL copyleft licenses in the production closure.\n\n`

md += `## Bundled binaries (compiled from source)\n\n`
md += `| Component | Version | License | Source |\n|---|---|---|---|\n`
for (const b of binaries) md += `| ${b.name} | ${b.version} | ${b.license} | ${b.repository} |\n`
md += `\nBoth are statically compiled in multi-stage builds (see \`packages/backend/Dockerfile\`).\n`
md += `Their bundled Go transitive dependencies are not enumerated here — run\n`
md += `\`go-licenses report\` in the build stages for the full Go attribution (tracked as a follow-up).\n\n`

md += `## npm packages (production closure)\n\n`
md += `| Package | Version | License |\n|---|---|---|\n`
for (const d of npm) md += `| ${d.name} | ${d.version} | ${d.license} |\n`
md += `\n`

fs.writeFileSync(path.join(ROOT, 'THIRD_PARTY_LICENSES.md'), md)

console.log(`\nWrote THIRD_PARTY_LICENSES.{json,md}: ${npm.length} npm packages, ${binaries.length} binaries.`)
if (copyleft.length) {
  console.warn(`COPYLEFT FOUND (${copyleft.length}): ${copyleft.map((d) => d.name).join(', ')}`)
  process.exitCode = 0 // report-only; CI can flip this to fail if desired
}
